#!/bin/bash
# clean
rm dist/*
rm -Rf .pytest_cache
# force coding style
python3 -m black .
# rebuild, install and test
python3 -m build && python3 -m pip install --force-reinstall dist/*.whl && \
python3 -m coverage run --source=moto_lib,moto_tar,moto_nl,moto_bas2lst,moto_lst2bas,moto_prettier --branch -m pytest && \
python3 -m coverage report -m && \
python3 -m coverage html 

